/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IReview } from "../IReview";

export class IReview__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReview {
    return new Contract(address, _abi, signerOrProvider) as IReview;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "bootcamp",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "courseAddress",
        type: "address",
      },
    ],
    name: "NewCourse",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "courseId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "reviewer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reviewUID",
        type: "string",
      },
    ],
    name: "NewReview",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "bootcamp",
        type: "address",
      },
      {
        internalType: "string",
        name: "bootcampURI",
        type: "string",
      },
    ],
    name: "addBootcamp",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "course",
        type: "address",
      },
      {
        internalType: "string",
        name: "courseURI",
        type: "string",
      },
    ],
    name: "addCourse",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "courseId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "reviewURI",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "rating",
        type: "uint256",
      },
      {
        internalType: "bytes32[]",
        name: "proof",
        type: "bytes32[]",
      },
      {
        internalType: "bytes32",
        name: "root",
        type: "bytes32",
      },
    ],
    name: "reviewCourse",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
