/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ReviewInterface extends ethers.utils.Interface {
  functions: {
    "addBootcamp(address)": FunctionFragment;
    "bootcamps(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "reviewCourse(address,string,uint256,bytes32[],bytes32)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addBootcamp", values: [string]): string;
  encodeFunctionData(
    functionFragment: "bootcamps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reviewCourse",
    values: [string, string, BigNumberish, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addBootcamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bootcamps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reviewCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "NewBootcamp(address)": EventFragment;
    "NewReview(address,address,string,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewBootcamp"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewReview"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class Review extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ReviewInterface;

  functions: {
    addBootcamp(
      bootcamp: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addBootcamp(address)"(
      bootcamp: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    bootcamps(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "bootcamps(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    reviewCourse(
      courseAddress: string,
      reviewCID: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "reviewCourse(address,string,uint256,bytes32[],bytes32)"(
      courseAddress: string,
      reviewCID: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  addBootcamp(
    bootcamp: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addBootcamp(address)"(
    bootcamp: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  bootcamps(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "bootcamps(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  reviewCourse(
    courseAddress: string,
    reviewCID: string,
    rating: BigNumberish,
    proof: BytesLike[],
    root: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "reviewCourse(address,string,uint256,bytes32[],bytes32)"(
    courseAddress: string,
    reviewCID: string,
    rating: BigNumberish,
    proof: BytesLike[],
    root: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    addBootcamp(bootcamp: string, overrides?: CallOverrides): Promise<void>;

    "addBootcamp(address)"(
      bootcamp: string,
      overrides?: CallOverrides
    ): Promise<void>;

    bootcamps(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "bootcamps(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    reviewCourse(
      courseAddress: string,
      reviewCID: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "reviewCourse(address,string,uint256,bytes32[],bytes32)"(
      courseAddress: string,
      reviewCID: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    NewBootcamp(bootcamp: string | null): EventFilter;

    NewReview(
      course: string | null,
      reviewer: string | null,
      reviewURI: null,
      rating: null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    addBootcamp(bootcamp: string, overrides?: Overrides): Promise<BigNumber>;

    "addBootcamp(address)"(
      bootcamp: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    bootcamps(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bootcamps(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    reviewCourse(
      courseAddress: string,
      reviewCID: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "reviewCourse(address,string,uint256,bytes32[],bytes32)"(
      courseAddress: string,
      reviewCID: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addBootcamp(
      bootcamp: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addBootcamp(address)"(
      bootcamp: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    bootcamps(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "bootcamps(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    reviewCourse(
      courseAddress: string,
      reviewCID: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "reviewCourse(address,string,uint256,bytes32[],bytes32)"(
      courseAddress: string,
      reviewCID: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
