/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface CourseInterface extends ethers.utils.Interface {
  functions: {
    "getCourseCID()": FunctionFragment;
    "graduate(bytes32,string)": FunctionFragment;
    "initialize(string,address)": FunctionFragment;
    "isCertified(bytes32[],bytes32,bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getCourseCID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "graduate",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isCertified",
    values: [BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCourseCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "graduate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCertified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "Graduate(bytes32,string)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Graduate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class Course extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: CourseInterface;

  functions: {
    getCourseCID(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getCourseCID()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    graduate(
      _hash: BytesLike,
      _cid: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "graduate(bytes32,string)"(
      _hash: BytesLike,
      _cid: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initialize(
      _courseCID: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(string,address)"(
      _courseCID: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isCertified(
      proof: BytesLike[],
      leaf: BytesLike,
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isCertified(bytes32[],bytes32,bytes32)"(
      proof: BytesLike[],
      leaf: BytesLike,
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    owner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getCourseCID(overrides?: CallOverrides): Promise<string>;

  "getCourseCID()"(overrides?: CallOverrides): Promise<string>;

  graduate(
    _hash: BytesLike,
    _cid: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "graduate(bytes32,string)"(
    _hash: BytesLike,
    _cid: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initialize(
    _courseCID: string,
    _owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(string,address)"(
    _courseCID: string,
    _owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isCertified(
    proof: BytesLike[],
    leaf: BytesLike,
    root: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isCertified(bytes32[],bytes32,bytes32)"(
    proof: BytesLike[],
    leaf: BytesLike,
    root: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getCourseCID(overrides?: CallOverrides): Promise<string>;

    "getCourseCID()"(overrides?: CallOverrides): Promise<string>;

    graduate(
      _hash: BytesLike,
      _cid: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "graduate(bytes32,string)"(
      _hash: BytesLike,
      _cid: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(
      _courseCID: string,
      _owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(string,address)"(
      _courseCID: string,
      _owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isCertified(
      proof: BytesLike[],
      leaf: BytesLike,
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isCertified(bytes32[],bytes32,bytes32)"(
      proof: BytesLike[],
      leaf: BytesLike,
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    Graduate(merkelProof: null, courseCID: null): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    getCourseCID(overrides?: CallOverrides): Promise<BigNumber>;

    "getCourseCID()"(overrides?: CallOverrides): Promise<BigNumber>;

    graduate(
      _hash: BytesLike,
      _cid: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "graduate(bytes32,string)"(
      _hash: BytesLike,
      _cid: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initialize(
      _courseCID: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(string,address)"(
      _courseCID: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isCertified(
      proof: BytesLike[],
      leaf: BytesLike,
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isCertified(bytes32[],bytes32,bytes32)"(
      proof: BytesLike[],
      leaf: BytesLike,
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getCourseCID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getCourseCID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    graduate(
      _hash: BytesLike,
      _cid: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "graduate(bytes32,string)"(
      _hash: BytesLike,
      _cid: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _courseCID: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(string,address)"(
      _courseCID: string,
      _owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isCertified(
      proof: BytesLike[],
      leaf: BytesLike,
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isCertified(bytes32[],bytes32,bytes32)"(
      proof: BytesLike[],
      leaf: BytesLike,
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
