/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IReviewInterface extends ethers.utils.Interface {
  functions: {
    "addBootcamp(address,string)": FunctionFragment;
    "addCourse(address,string)": FunctionFragment;
    "reviewCourse(uint256,string,uint256,bytes32[],bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addBootcamp",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addCourse",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "reviewCourse",
    values: [BigNumberish, string, BigNumberish, BytesLike[], BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addBootcamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addCourse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reviewCourse",
    data: BytesLike
  ): Result;

  events: {
    "NewCourse(address,address)": EventFragment;
    "NewReview(uint256,address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewCourse"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewReview"): EventFragment;
}

export class IReview extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IReviewInterface;

  functions: {
    addBootcamp(
      bootcamp: string,
      bootcampURI: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "addBootcamp(address,string)"(
      bootcamp: string,
      bootcampURI: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    addCourse(
      course: string,
      courseURI: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addCourse(address,string)"(
      course: string,
      courseURI: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    reviewCourse(
      courseId: BigNumberish,
      reviewURI: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "reviewCourse(uint256,string,uint256,bytes32[],bytes32)"(
      courseId: BigNumberish,
      reviewURI: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  addBootcamp(
    bootcamp: string,
    bootcampURI: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "addBootcamp(address,string)"(
    bootcamp: string,
    bootcampURI: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  addCourse(
    course: string,
    courseURI: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addCourse(address,string)"(
    course: string,
    courseURI: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  reviewCourse(
    courseId: BigNumberish,
    reviewURI: string,
    rating: BigNumberish,
    proof: BytesLike[],
    root: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "reviewCourse(uint256,string,uint256,bytes32[],bytes32)"(
    courseId: BigNumberish,
    reviewURI: string,
    rating: BigNumberish,
    proof: BytesLike[],
    root: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    addBootcamp(
      bootcamp: string,
      bootcampURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "addBootcamp(address,string)"(
      bootcamp: string,
      bootcampURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addCourse(
      course: string,
      courseURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "addCourse(address,string)"(
      course: string,
      courseURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    reviewCourse(
      courseId: BigNumberish,
      reviewURI: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "reviewCourse(uint256,string,uint256,bytes32[],bytes32)"(
      courseId: BigNumberish,
      reviewURI: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    NewCourse(bootcamp: string | null, courseAddress: null): EventFilter;

    NewReview(
      courseId: null,
      reviewer: string | null,
      reviewUID: null
    ): EventFilter;
  };

  estimateGas: {
    addBootcamp(
      bootcamp: string,
      bootcampURI: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "addBootcamp(address,string)"(
      bootcamp: string,
      bootcampURI: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    addCourse(
      course: string,
      courseURI: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addCourse(address,string)"(
      course: string,
      courseURI: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    reviewCourse(
      courseId: BigNumberish,
      reviewURI: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "reviewCourse(uint256,string,uint256,bytes32[],bytes32)"(
      courseId: BigNumberish,
      reviewURI: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addBootcamp(
      bootcamp: string,
      bootcampURI: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "addBootcamp(address,string)"(
      bootcamp: string,
      bootcampURI: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    addCourse(
      course: string,
      courseURI: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addCourse(address,string)"(
      course: string,
      courseURI: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    reviewCourse(
      courseId: BigNumberish,
      reviewURI: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "reviewCourse(uint256,string,uint256,bytes32[],bytes32)"(
      courseId: BigNumberish,
      reviewURI: string,
      rating: BigNumberish,
      proof: BytesLike[],
      root: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
